"""Reset changes

Revision ID: aa1e4b4ef323
Revises: c6748d5b1e5a
Create Date: 2022-06-05 16:13:33.112185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1e4b4ef323'
down_revision = 'c6748d5b1e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_names', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('uq_user_names', ['username'])

    # ### end Alembic commands ###
