"""New database after ALTER broke the old one

Revision ID: d467144d3911
Revises: 
Create Date: 2022-05-29 12:37:51.456433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd467144d3911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('coordinates', sa.String(length=64), nullable=False),
    sa.Column('previewImage', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=45), nullable=False),
    sa.Column('review', sa.String(length=1024), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('trail', sa.String(length=45), nullable=False),
    sa.Column('previewImage', sa.String(length=255), nullable=False),
    sa.Column('technicalDifficulty', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('emailAdresse', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('rolle', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('emailAdresse')
    )
    op.create_table('HighlightImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlightId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['highlightId'], ['Highlight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HighlightInRoute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.Column('highlightId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['highlightId'], ['Highlight.id'], ),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReviewImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['reviewId'], ['Review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RouteImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TagOfRoute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=45), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagOfRoute')
    op.drop_table('RouteImages')
    op.drop_table('ReviewImage')
    op.drop_table('HighlightInRoute')
    op.drop_table('HighlightImage')
    op.drop_table('User')
    op.drop_table('Route')
    op.drop_table('Review')
    op.drop_table('Highlight')
    # ### end Alembic commands ###
