"""empty message

Revision ID: e93f7d79e9c1
Revises: eaeceff01558
Create Date: 2022-06-14 20:19:10.802583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93f7d79e9c1'
down_revision = 'eaeceff01558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('previewImage', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=15), nullable=False),
    sa.Column('longitude', sa.String(length=15), nullable=False),
    sa.Column('creator', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['User.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=45), nullable=False),
    sa.Column('review', sa.String(length=1024), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['User.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('trail', sa.String(length=45), nullable=False),
    sa.Column('previewImage', sa.String(length=255), nullable=False),
    sa.Column('technicalDifficulty', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('startLon', sa.String(length=15), nullable=False),
    sa.Column('startLat', sa.String(length=15), nullable=False),
    sa.Column('creator', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['User.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HighlightImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlightId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['highlightId'], ['Highlight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HighlightInRoute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.Column('highlightId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['highlightId'], ['Highlight.id'], ),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReviewImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['reviewId'], ['Review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RouteImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('creator', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['User.username'], ),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TagOfRoute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=45), nullable=False),
    sa.Column('routeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagOfRoute')
    op.drop_table('RouteImages')
    op.drop_table('ReviewImage')
    op.drop_table('HighlightInRoute')
    op.drop_table('HighlightImage')
    op.drop_table('Route')
    op.drop_table('Review')
    op.drop_table('Highlight')
    # ### end Alembic commands ###
