"""added member_since clumn for users

Revision ID: f827b3178215
Revises: aa1e4b4ef323
Create Date: 2022-06-08 15:53:08.044718

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f827b3178215'
down_revision = 'aa1e4b4ef323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_since', sa.String(length=10), nullable=False, server_default="01.01.2022"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('member_since')

    # ### end Alembic commands ###
