"""Added user ID not null

Revision ID: 296ea816932b
Revises: aa1e4b4ef323
Create Date: 2022-06-05 15:31:44.368957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296ea816932b'
down_revision = 'aa1e4b4ef323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_User')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_User',
    sa.Column('username', sa.VARCHAR(length=45), nullable=False),
    sa.Column('emailAdresse', sa.VARCHAR(length=45), nullable=False),
    sa.Column('password', sa.VARCHAR(length=45), nullable=False),
    sa.Column('rolle', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('emailAdresse'),
    sa.UniqueConstraint('username', name='uq_user_names')
    )
    # ### end Alembic commands ###
